# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-31 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='title',
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Name'),
        ),
    ]
