# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-31 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161231_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='device',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Username'),
        ),
    ]
