# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-01 16:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161231_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicefeature',
            name='check_interval',
        ),
        migrations.AddField(
            model_name='devicefeature',
            name='round_interval',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Round Interval(Seconds)'),
        ),
        migrations.AlterField(
            model_name='devicefeature',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Enabled?'),
        ),
        migrations.AlterField(
            model_name='devicefeature',
            name='feature',
            field=models.CharField(choices=[('ping', 'ping'), ('nmap', 'nmap')], max_length=128, verbose_name='Feature Name'),
        ),
    ]
