# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-04 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_devicefeature_last_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=128, null=True, verbose_name='Feature Name')),
                ('severity', models.SmallIntegerField(choices=[(5, 'Critical'), (4, 'Error'), (3, 'Warning'), (2, 'Info'), (1, 'Debug'), (0, 'Clear')], default=2, verbose_name='Severity')),
                ('summary', models.CharField(max_length=512, null=True, verbose_name='Summary')),
                ('message', models.TextField(max_length=10240, verbose_name='Message')),
                ('first_time', models.DateTimeField(auto_now_add=True, verbose_name='First Time')),
                ('last_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Time')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Count')),
                ('clear_time', models.DateTimeField(null=True, verbose_name='Clear Time')),
                ('notify_time', models.DateTimeField(null=True, verbose_name='Notify Time')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='core.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('type', models.CharField(max_length=128, verbose_name='Name')),
                ('severity', models.SmallIntegerField(choices=[(5, 'Critical'), (4, 'Error'), (3, 'Warning'), (2, 'Info'), (1, 'Debug'), (0, 'Clear')], default=2, verbose_name='Severity')),
                ('trigger_time', models.DateTimeField(null=True, verbose_name='Trigger Time')),
                ('clear_time', models.DateTimeField(null=True, verbose_name='Clear Time')),
                ('active', models.BooleanField(default=True, verbose_name='Active?')),
                ('data', jsonfield.fields.JSONField(default=dict, verbose_name='Data')),
                ('device_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threshold', to='core.DeviceFeature')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='threshold',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='core.Threshold'),
        ),
    ]
