# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-05 18:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20170105_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('received', 'Received')], default='sent', max_length=32, verbose_name='Status')),
                ('notify_media', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('web', 'Web Dashboard')], max_length=32, verbose_name='Notify Type')),
                ('subject', models.CharField(blank=True, max_length=128, null=True, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('notify_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Notify Date/Time')),
                ('received_datetime', models.DateTimeField(blank=True, verbose_name='Received Date/Time')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAlertRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Enabled?')),
                ('notify_media', jsonfield.fields.JSONField(default=dict, verbose_name='Notify by')),
                ('rules', jsonfield.fields.JSONField(default=dict, verbose_name='Data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rule', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
