# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-05 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alertnotification_useralertrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertnotification',
            name='notify_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Notify Date/Time'),
        ),
        migrations.AlterField(
            model_name='alertnotification',
            name='received_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Received Date/Time'),
        ),
    ]
