# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-05 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170105_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='Seen?'),
        ),
    ]
