# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-25 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170111_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='tags',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Tags'),
        ),
    ]
