# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-26 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_device_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'permissions': (('access_device_secret_data', 'Can access device secret data'),)},
        ),
    ]
