# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-27 07:02
from __future__ import unicode_literals

from django.utils import timezone
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Device = apps.get_model("core", "Device")
    for device in Device.objects.using(db_alias).all():
        if device.status == 'up':
            device.last_seen = timezone.now()
            device.save()
        elif device.status == 'unknown':
            device.status = 'down'
            device.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170126_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(null=True, verbose_name='Last Seen'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down')], default='down', max_length=16, verbose_name='Status'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
