# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-29 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170127_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='useralertrule',
            name='custom_message',
            field=models.TextField(blank=True, max_length=10240, null=True, verbose_name='Custom Message'),
        ),
        migrations.AddField(
            model_name='useralertrule',
            name='custom_summary',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Custom Summary'),
        ),
    ]
