# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-12 09:46
from __future__ import unicode_literals

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Device = apps.get_model("core", "Device")
    for device in Device.objects.using(db_alias).filter(mac__isnull=False).exclude(mac=''):
        device.mac = device.mac.lower()
        device.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_device_web_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='address',
            field=models.GenericIPAddressField(verbose_name='IP Address'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
