# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-05 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20170312_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='warranty_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
